# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: anyasand/pb/anya.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='anyasand/pb/anya.proto',
  package='anya',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16\x61nyasand/pb/anya.proto\x12\x04\x61nya\"\x1f\n\x03Pos\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"M\n\x04Word\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04read\x18\x02 \x01(\t\x12\x0e\n\x06pos_id\x18\x03 \x01(\x05\x12\x0c\n\x04\x63ost\x18\x04 \x01(\x02\x12\x0b\n\x03vec\x18\x05 \x03(\x02\"E\n\nDictionary\x12\x1c\n\tpositions\x18\x01 \x03(\x0b\x32\t.anya.Pos\x12\x19\n\x05words\x18\x02 \x03(\x0b\x32\n.anya.Wordb\x06proto3')
)




_POS = _descriptor.Descriptor(
  name='Pos',
  full_name='anya.Pos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='anya.Pos.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='anya.Pos.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=63,
)


_WORD = _descriptor.Descriptor(
  name='Word',
  full_name='anya.Word',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='anya.Word.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='read', full_name='anya.Word.read', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos_id', full_name='anya.Word.pos_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cost', full_name='anya.Word.cost', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vec', full_name='anya.Word.vec', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=142,
)


_DICTIONARY = _descriptor.Descriptor(
  name='Dictionary',
  full_name='anya.Dictionary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='positions', full_name='anya.Dictionary.positions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='words', full_name='anya.Dictionary.words', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=213,
)

_DICTIONARY.fields_by_name['positions'].message_type = _POS
_DICTIONARY.fields_by_name['words'].message_type = _WORD
DESCRIPTOR.message_types_by_name['Pos'] = _POS
DESCRIPTOR.message_types_by_name['Word'] = _WORD
DESCRIPTOR.message_types_by_name['Dictionary'] = _DICTIONARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pos = _reflection.GeneratedProtocolMessageType('Pos', (_message.Message,), dict(
  DESCRIPTOR = _POS,
  __module__ = 'anyasand.pb.anya_pb2'
  # @@protoc_insertion_point(class_scope:anya.Pos)
  ))
_sym_db.RegisterMessage(Pos)

Word = _reflection.GeneratedProtocolMessageType('Word', (_message.Message,), dict(
  DESCRIPTOR = _WORD,
  __module__ = 'anyasand.pb.anya_pb2'
  # @@protoc_insertion_point(class_scope:anya.Word)
  ))
_sym_db.RegisterMessage(Word)

Dictionary = _reflection.GeneratedProtocolMessageType('Dictionary', (_message.Message,), dict(
  DESCRIPTOR = _DICTIONARY,
  __module__ = 'anyasand.pb.anya_pb2'
  # @@protoc_insertion_point(class_scope:anya.Dictionary)
  ))
_sym_db.RegisterMessage(Dictionary)


# @@protoc_insertion_point(module_scope)
