# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: egoisticlily.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x65goisticlily.proto\x12\x0c\x65goisticlily\"\x1c\n\nConvertReq\x12\x0e\n\x06in_str\x18\x01 \x01(\t\".\n\x0b\x43onvertResp\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07out_str\x18\x02 \x01(\t\"#\n\x11PartialConvertReq\x12\x0e\n\x06in_str\x18\x01 \x01(\t\"5\n\x12PartialConvertResp\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07out_str\x18\x02 \x03(\t2\xae\x01\n\x13\x45goisticLilyService\x12@\n\x07\x43onvert\x12\x18.egoisticlily.ConvertReq\x1a\x19.egoisticlily.ConvertResp\"\x00\x12U\n\x0ePartialConvert\x12\x1f.egoisticlily.PartialConvertReq\x1a .egoisticlily.PartialConvertResp\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'egoisticlily_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONVERTREQ._serialized_start=36
  _CONVERTREQ._serialized_end=64
  _CONVERTRESP._serialized_start=66
  _CONVERTRESP._serialized_end=112
  _PARTIALCONVERTREQ._serialized_start=114
  _PARTIALCONVERTREQ._serialized_end=149
  _PARTIALCONVERTRESP._serialized_start=151
  _PARTIALCONVERTRESP._serialized_end=204
  _EGOISTICLILYSERVICE._serialized_start=207
  _EGOISTICLILYSERVICE._serialized_end=381
# @@protoc_insertion_point(module_scope)
