# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import egoisticlily_pb2 as egoisticlily__pb2


class EgoisticLilyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Convert = channel.unary_unary(
                '/egoisticlily.EgoisticLilyService/Convert',
                request_serializer=egoisticlily__pb2.ConvertReq.SerializeToString,
                response_deserializer=egoisticlily__pb2.ConvertResp.FromString,
                )
        self.PartialConvert = channel.unary_unary(
                '/egoisticlily.EgoisticLilyService/PartialConvert',
                request_serializer=egoisticlily__pb2.PartialConvertReq.SerializeToString,
                response_deserializer=egoisticlily__pb2.PartialConvertResp.FromString,
                )


class EgoisticLilyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Convert(self, request, context):
        """多分変換
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialConvert(self, request, context):
        """多分部分変換
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EgoisticLilyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Convert': grpc.unary_unary_rpc_method_handler(
                    servicer.Convert,
                    request_deserializer=egoisticlily__pb2.ConvertReq.FromString,
                    response_serializer=egoisticlily__pb2.ConvertResp.SerializeToString,
            ),
            'PartialConvert': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialConvert,
                    request_deserializer=egoisticlily__pb2.PartialConvertReq.FromString,
                    response_serializer=egoisticlily__pb2.PartialConvertResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'egoisticlily.EgoisticLilyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EgoisticLilyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Convert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/egoisticlily.EgoisticLilyService/Convert',
            egoisticlily__pb2.ConvertReq.SerializeToString,
            egoisticlily__pb2.ConvertResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PartialConvert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/egoisticlily.EgoisticLilyService/PartialConvert',
            egoisticlily__pb2.PartialConvertReq.SerializeToString,
            egoisticlily__pb2.PartialConvertResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
